# Generated by Django 5.1.4 on 2026-04-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='task_counter',
            field=models.PositiveIntegerField(default=0, help_text='Contador secuencial para IDs de tareas'),
        ),
    ]
