# Generated by Django 6.0.4 on 2026-04-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_task_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='is_done_column',
            field=models.BooleanField(default=False, help_text='¿Es esta la columna donde se completan las tareas?'),
        ),
    ]
