# Generated by Django 5.1.4 on 2026-05-07 14:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_column_is_done_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMetricSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('velocity', models.FloatField(default=0, help_text='Puntos completados en el último intervalo')),
                ('throughput', models.IntegerField(default=0, help_text='Tareas completadas')),
                ('cycle_time_avg', models.FloatField(default=0, help_text='Promedio de días en progreso')),
                ('flow_efficiency', models.FloatField(default=0, help_text='Ratio de tiempo activo vs total')),
                ('active_tasks_count', models.IntegerField(default=0)),
                ('completed_tasks_count', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='projects.project')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('project', 'date')},
            },
        ),
    ]
