# Generated by Django 5.1.4 on 2026-05-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectmetricsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmetricsnapshot',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
