# Generated by Django 6.0.4 on 2026-05-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('assignment', 'Asignación de tarea'), ('expiration', 'Vencimiento de sprint'), ('system', 'Sistema')], default='system', max_length=20),
        ),
    ]
