# Generated by Django 6.0.4 on 2026-05-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_assigned', 'Tarea Asignada'), ('task_moved', 'Tarea Movida'), ('task_comment', 'Nuevo Comentario'), ('custom_alert', 'Alerta de Sistema')], max_length=20),
        ),
    ]
