# Generated by Django 5.1.4 on 2026-08-12 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_assigned', 'Tarea Asignada'), ('task_moved', 'Tarea Movida'), ('task_comment', 'Nuevo Comentario'), ('custom_alert', 'Alerta de Sistema'), ('expiration', 'Vencimiento de Sprint')], max_length=20),
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_assigned', models.BooleanField(default=True)),
                ('task_moved', models.BooleanField(default=True)),
                ('task_comment', models.BooleanField(default=True)),
                ('custom_alert', models.BooleanField(default=True)),
                ('expiration', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencias de Notificación',
                'verbose_name_plural': 'Preferencias de Notificación',
                'db_table': 'notification_settings',
            },
        ),
    ]
