# Generated by Django 6.0.4 on 2026-05-06 20:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
        ('projects', '0003_alter_column_is_done_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('risk', 'Riesgo'), ('improvement', 'Mejora'), ('technical', 'Sugerencia Técnica')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('applied', 'Aplicada'), ('discarded', 'Descartada')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
