# Generated by Django 5.1.4 on 2026-05-10 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0002_aiconversation_aimessage'),
        ('projects', '0005_alter_projectmetricsnapshot_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='action_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiconversation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='aiproposal',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='aiproposal',
            name='description',
            field=models.TextField(),
        ),
    ]
