# Generated by Django 6.0.4 on 2026-05-12 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0002_recommendation'),
        ('intelligence', '0003_aimessage_action_metadata_and_more'),
    ]

    operations = [
    ]
