# Generated by Django 6.0.4 on 2026-04-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='acceptance_criteria',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
