# Generated by Django 6.0.4 on 2026-04-30 18:40
# Renumbered from 0004 to 0005 to avoid conflict with 0004_alter_task_options_task_order (from main branch)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_options_task_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='acceptance_criteria',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
