# Generated by Django 5.1.4 on 2026-05-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ai_assignee',
            field=models.CharField(blank=True, choices=[('orchestrator', 'Orchestrator'), ('backend_architect', 'Backend Architect'), ('frontend_specialist', 'Frontend Specialist'), ('database_expert', 'Database Expert'), ('ui_designer', 'UI Designer'), ('product_manager', 'Product Manager')], help_text='If assigned to an AI agent, specify the agent role.', max_length=50, null=True),
        ),
    ]
